language: generic

git:
  depth: 5

cache:
  directories:
    - /tmp/texlive

before_install:
  # Thanks to http://stackoverflow.com/a/32358866
  # Install modules into ~/perl5 using system perl
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - export PATH=$PATH:~/perl5/bin/
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm JSON
  - cpanm --notest https://github.com/brucemiller/LaTeXML.git

install:
  # Thanks to https://github.com/ustctug/ustcthesis
  - source ./.travis_install.sh

script:
  - make

notifications:
  email: false
